---
title: "R Notebook"
output: html_notebook
---



```{r}
install.packages("data.table")

library("dplyr")
library(httr)
library(jsonlite)

library(data.table)
```
```{r}

raw <- fread("C:\\Users\\donal\\Documents\\R Projects\\untappd\\untappd_data.csv")

dc1 <- raw %>% dplyr::select(c(beer_name,brewery_city,brewery_country,brewery_state,brewery_id,beer_type,beer_abv, beer_ibu,venue_city,venue_state,rating_score,created_at)) %>% mutate(
               beer_type_main = gsub( " .*$", "-", beer_type)) %>% filter(is.na(rating_score) != T)



dc2 <- dc1 %>% group_by(beer_type_main) %>% summarise(n = n(),
                                                      mean = mean(rating_score),
                                                      min = min(rating_score),
                                                      max = max(rating_score),
                                                      range = max - min)

dc2 <- dc1 %>% group_by(beer_type) %>% summarise(n = n(),
                                                      mean = mean(rating_score),
                                                      min = min(rating_score),
                                                      max = max(rating_score),
                                                      range = max - min) %>% 
                filter(n > 1)

head(dc1)

table(dc1$beer_type_main)
```



```{r}
# Multiple Linear Regression Example 
fit <- lm(rating_score ~ beer_type_main + beer_abv + beer_ibu, data=dc1)
summary(fit) # show results

# Other useful functions 
coefficients(fit) # model coefficients
confint(fit, level=0.95) # CIs for model parameters 
fitted(fit) # predicted values
residuals(fit) # residuals
anova(fit) # anova table 
vcov(fit) # covariance matrix for model parameters 
influence(fit) # regression diagnostics
```

```{r}
# diagnostic plots 
layout(matrix(c(1,2,3,4),2,2)) # optional 4 graphs/page 
plot(fit)
```

